
from pytruenas import TrueNASClient
from pytruenas.base import Namespace

import typing
class SystemAdvanced(
    Namespace
    ):
    _namespace:typing.Literal['system.advanced']
    def __init__(self, client:TrueNASClient) -> None: ...
    @typing.overload
    def config(self, 
    /) -> 'SystemAdvancedEntry': 
        """
        

        Parameters
        ----------
        Returns
        -------
        SystemAdvancedEntry:
            system_advanced_entry
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    @typing.overload
    def sed_global_password(self, 
    /) -> 'str': 
        """
        Returns configured global SED password.

        Parameters
        ----------
        Returns
        -------
        str:
            sed_global_password
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    @typing.overload
    def serial_port_choices(self, 
    /) -> 'dict[str]': 
        """
        Get available choices for `serialport`.

        Parameters
        ----------
        Returns
        -------
        dict[str]:
            serial_port_choices
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    @typing.overload
    def syslog_certificate_authority_choices(self, 
    /) -> 'dict[str]': 
        """
        Return choices of certificate authorities which can be used for `syslog_tls_certificate_authority`.

        Parameters
        ----------
        Returns
        -------
        dict[str]:
            Syslog Certificate Authority Choices
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    @typing.overload
    def syslog_certificate_choices(self, 
    /) -> 'dict[str]': 
        """
        Return choices of certificates which can be used for `syslog_tls_certificate`.

        Parameters
        ----------
        Returns
        -------
        dict[str]:
            Syslog Certificate Choices
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    @typing.overload
    def update(self, 
        system_advanced_update:'SystemAdvancedUpdate'={},
    /) -> 'SystemAdvancedUpdateReturns': 
        """
        Update System Advanced Service Configuration.
        
        `consolemenu` should be disabled if the menu at console is not desired. It will default to standard login
        in the console if disabled.
        
        `autotune` when enabled executes autotune script which attempts to optimize the system based on the installed
        hardware.
        
        When `syslogserver` is defined, logs of `sysloglevel` or above are sent.
        
        `consolemsg` is a deprecated attribute and will be removed in further releases. Please, use `consolemsg`
        attribute in the `system.general` plugin.
        
        `isolated_gpu_pci_ids` is a list of PCI ids which are isolated from host system.

        Parameters
        ----------
        system_advanced_update:
            system_advanced_update
        Returns
        -------
        SystemAdvancedUpdateReturns:
            system_advanced_update_returns
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    @typing.overload
    def update_gpu_pci_ids(self, 
        isolated_gpu_pci_ids:'list[str]',
    /) -> None: 
        """
        `isolated_gpu_pci_ids` is a list of PCI ids which are isolated from host system.

        Parameters
        ----------
        isolated_gpu_pci_ids:
            isolated_gpu_pci_ids
        Returns
        -------
        """
        ...
    SystemAdvancedEntry = typing.TypedDict('SystemAdvancedEntry', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })
    SystemAdvancedUpdate = typing.TypedDict('SystemAdvancedUpdate', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'sed_passwd':'str',
    })
    SystemAdvancedUpdateReturns = typing.TypedDict('SystemAdvancedUpdateReturns', {
            'advancedmode':'bool',
            'autotune':'bool',
            'kdump_enabled':'bool',
            'boot_scrub':'int',
            'consolemenu':'bool',
            'consolemsg':'bool',
            'debugkernel':'bool',
            'fqdn_syslog':'bool',
            'motd':'str',
            'powerdaemon':'bool',
            'serialconsole':'bool',
            'serialport':'str',
            'anonstats_token':'str',
            'serialspeed':'str',
            'swapondrive':'int',
            'overprovision':'typing.Optional[int]',
            'traceback':'bool',
            'uploadcrash':'bool',
            'anonstats':'bool',
            'sed_user':'str',
            'sysloglevel':'str',
            'syslogserver':'str',
            'syslog_transport':'str',
            'syslog_tls_certificate':'typing.Optional[int]',
            'syslog_tls_certificate_authority':'typing.Optional[int]',
            'isolated_gpu_pci_ids':'list[str]',
            'kernel_extra_options':'str',
            'id':'int',
    })

