
from pytruenas.base import Namespace
from pytruenas.mixins import ConfigMixin

import typing
from enum import Enum

class Ftp(ConfigMixin, Namespace):
    def __init__(self, client) -> None:
        super().__init__(client, 'ftp')

    class TlsPolicy(str,Enum):
        On = 'on'
        Off = 'off'
        Data = 'data'
        _data = '!data'
        Auth = 'auth'
        Ctrl = 'ctrl'
        CtrlData = 'ctrl+data'
        CtrlData = 'ctrl+!data'
        AuthData = 'auth+data'
        AuthData = 'auth+!data'
        ...
    FtpEntry = typing.TypedDict('FtpEntry', {
            'port':'int',
            'clients':'int',
            'ipconnections':'int',
            'loginattempt':'int',
            'timeout':'int',
            'timeout_notransfer':'int',
            'rootlogin':'bool',
            'onlyanonymous':'bool',
            'anonpath':'typing.Optional[str]',
            'onlylocal':'bool',
            'banner':'str',
            'filemask':'str',
            'dirmask':'str',
            'fxp':'bool',
            'resume':'bool',
            'defaultroot':'bool',
            'ident':'bool',
            'reversedns':'bool',
            'masqaddress':'str',
            'passiveportsmin':'int',
            'passiveportsmax':'int',
            'localuserbw':'int',
            'localuserdlbw':'int',
            'anonuserbw':'int',
            'anonuserdlbw':'int',
            'tls':'bool',
            'tls_policy':'TlsPolicy',
            'tls_opt_allow_client_renegotiations':'bool',
            'tls_opt_allow_dot_login':'bool',
            'tls_opt_allow_per_user':'bool',
            'tls_opt_common_name_required':'bool',
            'tls_opt_enable_diags':'bool',
            'tls_opt_export_cert_data':'bool',
            'tls_opt_no_empty_fragments':'bool',
            'tls_opt_no_session_reuse_required':'bool',
            'tls_opt_stdenvvars':'bool',
            'tls_opt_dns_name_required':'bool',
            'tls_opt_ip_address_required':'bool',
            'ssltls_certificate':'typing.Optional[int]',
            'options':'str',
            'id':'int',
    })
    FtpUpdate = typing.TypedDict('FtpUpdate', {
            'port':'int',
            'clients':'int',
            'ipconnections':'int',
            'loginattempt':'int',
            'timeout':'int',
            'timeout_notransfer':'int',
            'rootlogin':'bool',
            'onlyanonymous':'bool',
            'anonpath':'typing.Optional[str]',
            'onlylocal':'bool',
            'banner':'str',
            'filemask':'str',
            'dirmask':'str',
            'fxp':'bool',
            'resume':'bool',
            'defaultroot':'bool',
            'ident':'bool',
            'reversedns':'bool',
            'masqaddress':'str',
            'passiveportsmin':'int',
            'passiveportsmax':'int',
            'localuserbw':'int',
            'localuserdlbw':'int',
            'anonuserbw':'int',
            'anonuserdlbw':'int',
            'tls':'bool',
            'tls_policy':'TlsPolicy',
            'tls_opt_allow_client_renegotiations':'bool',
            'tls_opt_allow_dot_login':'bool',
            'tls_opt_allow_per_user':'bool',
            'tls_opt_common_name_required':'bool',
            'tls_opt_enable_diags':'bool',
            'tls_opt_export_cert_data':'bool',
            'tls_opt_no_empty_fragments':'bool',
            'tls_opt_no_session_reuse_required':'bool',
            'tls_opt_stdenvvars':'bool',
            'tls_opt_dns_name_required':'bool',
            'tls_opt_ip_address_required':'bool',
            'ssltls_certificate':'typing.Optional[int]',
            'options':'str',
    })
    FtpUpdateReturns = typing.TypedDict('FtpUpdateReturns', {
            'port':'int',
            'clients':'int',
            'ipconnections':'int',
            'loginattempt':'int',
            'timeout':'int',
            'timeout_notransfer':'int',
            'rootlogin':'bool',
            'onlyanonymous':'bool',
            'anonpath':'typing.Optional[str]',
            'onlylocal':'bool',
            'banner':'str',
            'filemask':'str',
            'dirmask':'str',
            'fxp':'bool',
            'resume':'bool',
            'defaultroot':'bool',
            'ident':'bool',
            'reversedns':'bool',
            'masqaddress':'str',
            'passiveportsmin':'int',
            'passiveportsmax':'int',
            'localuserbw':'int',
            'localuserdlbw':'int',
            'anonuserbw':'int',
            'anonuserdlbw':'int',
            'tls':'bool',
            'tls_policy':'TlsPolicy',
            'tls_opt_allow_client_renegotiations':'bool',
            'tls_opt_allow_dot_login':'bool',
            'tls_opt_allow_per_user':'bool',
            'tls_opt_common_name_required':'bool',
            'tls_opt_enable_diags':'bool',
            'tls_opt_export_cert_data':'bool',
            'tls_opt_no_empty_fragments':'bool',
            'tls_opt_no_session_reuse_required':'bool',
            'tls_opt_stdenvvars':'bool',
            'tls_opt_dns_name_required':'bool',
            'tls_opt_ip_address_required':'bool',
            'ssltls_certificate':'typing.Optional[int]',
            'options':'str',
            'id':'int',
    })
