
from pytruenas.base import Namespace
from pytruenas.mixins import TableExtMixin

import typing
class Vm(TableExtMixin, Namespace):
    def __init__(self, client) -> None:
        super().__init__(client, 'vm')

    BootloaderOptions = typing.TypedDict('BootloaderOptions', {
            'UEFI':'str',
            'UEFI_CSM':'str',
    })
    VmCreate = typing.TypedDict('VmCreate', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
    })
    Status = typing.TypedDict('Status', {
            'state':'str',
            'pid':'typing.Optional[int]',
            'domain_state':'str',
    })
    VmCreateReturns = typing.TypedDict('VmCreateReturns', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
            'devices':'list',
            'status':'Status',
            'id':'int',
    })
    VmDelete = typing.TypedDict('VmDelete', {
            'zvols':'bool',
            'force':'bool',
    })
    CpuFlags = typing.TypedDict('CpuFlags', {
            'intel_vmx':'bool',
            'unrestricted_guest':'bool',
            'amd_rvi':'bool',
            'amd_asids':'bool',
    })
    VmDeviceEntry = typing.TypedDict('VmDeviceEntry', {
            'dtype':'str',
            'vm':'int',
            'attributes':'dict[str]',
            'order':'typing.Optional[int]',
            'id':'int',
    })
    Options = typing.TypedDict('Options', {
            'protocol':'str',
    })
    DisplayDevicesUri = typing.TypedDict('DisplayDevicesUri', {
            'error':'typing.Optional[str]',
            'uri':'typing.Optional[str]',
    })
    QueryOptionsGetInstance = typing.TypedDict('QueryOptionsGetInstance', {
            'relationships':'bool',
            'extend':'typing.Optional[str]',
            'extend_context':'typing.Optional[str]',
            'prefix':'typing.Optional[str]',
            'extra':'dict[str]',
            'order_by':'list',
            'select':'list',
            'count':'bool',
            'get':'bool',
            'offset':'int',
            'limit':'int',
            'force_sql_filters':'bool',
    })
    GetVmMemoryInfo = typing.TypedDict('GetVmMemoryInfo', {
            'minimum_memory_requested':'int',
            'total_memory_requested':'int',
            'overcommit_required':'bool',
            'memory_req_fulfilled_after_overcommit':'bool',
            'arc_to_shrink':'typing.Optional[int]',
            'current_arc_max':'int',
            'arc_min':'int',
            'arc_max_after_shrink':'int',
            'actual_vm_requested_memory':'int',
    })
    VmemoryInUse = typing.TypedDict('VmemoryInUse', {
            'RNP':'int',
            'PRD':'int',
            'RPRD':'int',
    })
    AvailableDisplayPort = typing.TypedDict('AvailableDisplayPort', {
            'port':'int',
            'web':'int',
    })
    QueryOptions = typing.TypedDict('QueryOptions', {
            'relationships':'bool',
            'extend':'typing.Optional[str]',
            'extend_context':'typing.Optional[str]',
            'prefix':'typing.Optional[str]',
            'extra':'dict[str]',
            'order_by':'list',
            'select':'list',
            'count':'bool',
            'get':'bool',
            'offset':'int',
            'limit':'int',
            'force_sql_filters':'bool',
    })
    Status_ = typing.TypedDict('Status_', {
            'state':'str',
            'pid':'typing.Optional[int]',
            'domain_state':'str',
    })
    VmEntry = typing.TypedDict('VmEntry', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
            'devices':'list',
            'status':'Status_',
            'id':'int',
    })
    Status__ = typing.TypedDict('Status__', {
            'state':'str',
            'pid':'typing.Optional[int]',
            'domain_state':'str',
    })
    VmEntry_ = typing.TypedDict('VmEntry_', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
            'devices':'list',
            'status':'Status__',
            'id':'int',
    })
    Status___ = typing.TypedDict('Status___', {
            'state':'str',
            'pid':'typing.Optional[int]',
            'domain_state':'str',
    })
    VmEntry__ = typing.TypedDict('VmEntry__', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
            'devices':'list',
            'status':'Status___',
            'id':'int',
    })
    ResolutionChoices = typing.TypedDict('ResolutionChoices', {
            '1920x1200':'str',
            '1920x1080':'str',
            '1600x1200':'str',
            '1600x900':'str',
            '1400x1050':'str',
            '1280x1024':'str',
            '1280x720':'str',
            '1024x768':'str',
            '800x600':'str',
            '640x480':'str',
    })
    Options_ = typing.TypedDict('Options_', {
            'overcommit':'bool',
    })
    VmStatus = typing.TypedDict('VmStatus', {
            'state':'str',
            'pid':'typing.Optional[int]',
            'domain_state':'str',
    })
    Options__ = typing.TypedDict('Options__', {
            'force':'bool',
            'force_after_timeout':'bool',
    })
    VmUpdate = typing.TypedDict('VmUpdate', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
            'id':'int',
    })
    Status____ = typing.TypedDict('Status____', {
            'state':'str',
            'pid':'typing.Optional[int]',
            'domain_state':'str',
    })
    VmUpdateReturns = typing.TypedDict('VmUpdateReturns', {
            'command_line_args':'str',
            'cpu_mode':'str',
            'cpu_model':'typing.Optional[str]',
            'name':'str',
            'description':'str',
            'vcpus':'int',
            'cores':'int',
            'threads':'int',
            'cpuset':'typing.Optional[str]',
            'nodeset':'typing.Optional[str]',
            'pin_vcpus':'bool',
            'suspend_on_snapshot':'bool',
            'trusted_platform_module':'bool',
            'memory':'int',
            'min_memory':'typing.Optional[int]',
            'hyperv_enlightenments':'bool',
            'bootloader':'str',
            'bootloader_ovmf':'str',
            'autostart':'bool',
            'hide_from_msr':'bool',
            'ensure_display_device':'bool',
            'time':'str',
            'shutdown_timeout':'int',
            'arch_type':'typing.Optional[str]',
            'machine_type':'typing.Optional[str]',
            'uuid':'typing.Optional[str]',
            'devices':'list',
            'status':'Status____',
            'id':'int',
    })
    VirtualizationDetails = typing.TypedDict('VirtualizationDetails', {
            'supported':'bool',
            'error':'typing.Optional[str]',
    })
