
from pytruenas import Namespace, TrueNASClient
import typing as _ty
class Truecommand(Namespace):
    _namespace:_ty.Literal['truecommand']
    def __init__(self, client:TrueNASClient) -> None: ...
    @_ty.overload
    def config(self, 
    /) -> 'dict[str]': 
        """
        

        Parameters
        ----------
        Returns
        -------
        dict[str]:
            truecommand_entry
        """
        ...
    @_ty.overload
    def connected(self, 
    /) -> 'dict[str]': 
        """
        Returns information which shows if system has an authenticated api key
        and has initiated a VPN connection with TrueCommand.

        Parameters
        ----------
        Returns
        -------
        dict[str]:
            truecommand_connected
        """
        ...
    @_ty.overload
    def update(self, 
        truecommand_update:'dict[str]'={},
    /) -> 'dict[str]': 
        """
        Update Truecommand service settings.
        
        `api_key` is a valid API key generated by iX Portal.

        Parameters
        ----------
        truecommand_update:
            truecommand_update
        Returns
        -------
        dict[str]:
            truecommand_update_returns
        """
        ...
